### ISSUE TITLE
Need tool to get dask dataframes from config files

### ISSUE THREAD

**Issue by acampove** [scikit-hep/uproot5#1441]
Hi,

I am looking for something like:

```python
ddfg = DDataFrameGetter(config_path='file.yaml')
ddf  = ddfg.get_dataframe()
```

where `file.yaml` has:

```yaml
tree   : tree_name
samples:
  main :
    - /tmp/tests/dmu/rfile/main/file_001.root
    - /tmp/tests/dmu/rfile/main/file_002.root
    - /tmp/tests/dmu/rfile/main/file_003.root
  frnd :
    - /tmp/tests/dmu/rfile/frnd/file_001.root
    - /tmp/tests/dmu/rfile/frnd/file_002.root
    - /tmp/tests/dmu/rfile/frnd/file_003.root
```

Cheers.
